# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


gupshup.api-key=o6cjnovazmsj3vfe5qebjzjnd2l1aqbh
gupshup.source-number=918237807923

# ===============================
# ACTUATOR HEALTH CHECK (DOCKER)
# ===============================

# Actuator runs on separate port
management.server.port=8081

# expose only health endpoint
management.endpoints.web.exposure.include=health

# enable liveness & readiness probes
management.endpoint.health.probes.enabled=true

# do not expose sensitive details publicly
management.endpoint.health.show-details=never


# ===============================
# APP CONFIG
# ===============================
gstValue=18.0