spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

gstValue=18.0
gupshup.api-key={GUPSHUP_API_KEY}
gupshup.source-number={GUPSHUP_SOURCE_NUMBER}

# Actuator runs on separate port (recommended for Docker)
management.server.port=8081

# expose only health endpoint
management.endpoints.web.exposure.include=health

# enable liveness & readiness probes
management.endpoint.health.probes.enabled=true

# do not expose sensitive details publicly
management.endpoint.health.show-details=never